[theme]
# Light theme alternative
base = "light"
primaryColor = "#1DB954"  # Spotify green
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray background
textColor = "#262730"  # Dark text

# Font configuration
font = "sans serif"

[server]
runOnSave = true


